config/routes.rb
Rails.application.routes.draw do
  resources :boards
  resources :boards do
    resources :holds
    resources :problems

  end
  resources :holds


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  validates :name, presence: true, length: { minimum:5 }
  validates :imageUrl, presence: true, length: { minimum:5 }
  has_many :holds, dependent: :destroy
  has_many :problems, dependent: :destroy
end

app/models/hold.rb
class Hold < ApplicationRecord
  belongs_to :board
  has_and_belongs_to_many :problems
end

app/models/problem.rb
class Problem < ApplicationRecord
  belongs_to :board
  has_and_belongs_to_many :holds

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def list
  end
  def new
    @board = Board.new
  end
  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to @board
    else
      render 'new'
    end
  end
  def update
    @board = Board.find(params[:id])
    @patchModel = Board.new(board_params)
    @board.holds = @patchModel.holds
    @board.save
  end
  def show
    @board = Board.find(params[:id])
  end
  private
  def board_params
    params.require(:board).permit(:name, :imageUrl, :holds)
  end
end

app/controllers/holds_controller.rb
class HoldsController < ApplicationController
  def list
  end
  def new
    @hold = Hold.new
  end
  def create
    @hold = Hold.new(hold_params)
    if @hold.save
      redirect_to @hold
    else
      render 'new'
    end
  end
  def show
    @hold = Hold.find(params[:id])
    render json: @hold
  end

  def destroy

    @hold = Hold.find(params[:id])
    @hold.destroy


  end
  private
  def hold_params
    params.require(:hold).permit(:x, :y, :board_id)
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController

  def index
    @board = Board.find(params[:board_id])
  end
  def new
    @board = Board.find(params[:board_id])
  end
  def show
    @problem = Problem.where(id: params[:id], board_id: params[:board_id]).first()
    @holds = @problem.holds
    logger.debug "New problem: #{@problem.attributes.inspect}"

  end
  def create
    @problem = Problem.new(problem_params)
    hold_params[:holds].each do | hold |

      @problem.holds << Hold.find(hold[:id])
    end

    if @problem.save
      render json: @problem
    else
      render 'new'
    end
  end
  private
  def problem_params
    params.require(:problem).permit(:board_id, :name)
  end
  def hold_params
    params.permit(holds: [:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/holds_helper.rb
module HoldsHelper
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/boards/list.html.erb
<h1>Board#list</h1>
<p>Find me in app/views/board/list.html.erb</p>

app/views/boards/new.html.erb
<h1>New board!</h1>
<%= form_with scope: :board, url: boards_path, local: true do |form| %>
<% if @board.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@board.errors.count, "error") %> prohibited
      this article from being saved:
    </h2>
    <ul>
      <% @board.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="form group">
   <%= form.label :name %><br>
   <%= form.text_field :name %>
 </div>

 <div class="form group">
   <%= form.label :imageUrl %><br>
   <%= form.text_field :imageUrl %>
 </div>

 <div class="form group">
   <%= form.submit %>
 </div>
<% end %>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>

<div class="row">
  <div class="col-sm-12">
    <div id="boardApp" />
  </div>
</div>
<script type="text/babel">


const board_id = <%= @board.id %>;
const boardHolds = (<%=raw @board.holds.to_json %>).map((hold) => {return { id: hold.id, position:{x: hold.x, y: hold.y}}});
class Marker extends React.Component{
  render() {
    const markerPosition = {position: 'absolute', left: this.props.x * 100 + '%', top: this.props.y * 100+ '%'};
    return (
      <svg width="3%" height="3%" style={markerPosition} xmlns="http://www.w3.org/2000/svg">
        <circle cx="50%" cy="50%" r="45%" stroke="red" stroke-width="5" fill="grey" fill-opacity="0.25" opacity="0.5" />
      </svg>
    )
  }
};

class Board extends React.Component{
  constructor (props) {
    super(props);
    this.state = { markers: boardHolds };
    this.addMarker = this.addMarker.bind(this);
    this.clearMarkers = this.clearMarkers.bind(this);
    this.undo = this.undo.bind(this);
  }
  addMarker(e) {
    let boardImage = document.getElementById('boardImage');
    let markers = this.state.markers;
    const newId = markers.length;
    const imageWidth = boardImage.offsetWidth;
    const imageHeight = boardImage.offsetHeight;

    const x = (e.nativeEvent.offsetX - (imageWidth/100*1.5))/(imageWidth);
    const y = (e.nativeEvent.offsetY - (imageHeight/100*1.5))/(imageHeight);

    fetch('/holds/', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        board_id: board_id,
        x: x,
        y: y
      })

    }).then((response)=>{
      return response.json()
    }).then((jsonResponse) => {
      const newMarker = { id: jsonResponse.id, position:{x: jsonResponse.x, y: jsonResponse.y}};
      markers = markers.concat(newMarker);
      this.setState({markers: markers});
    });
  }

  undo(e) {
    let markers = this.state.markers;
    const markerToDelete = markers[markers.length-1];
    markers.pop();
    this.setState({markers: markers});

    fetch('/boards/' + board_id + '/holds/' + markerToDelete.id + '/', {
      method: 'DELETE',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      }
    }).then(() => {
      this.setState({markers: markers});

    }
    )
  }
  clearMarkers(e) {
    const markers = this.state.markers;

    fetch('/boards/' + board_id + '/', {
      method: 'PATCH',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        board:{
          holds: []
        }
      })
    })


    this.setState({ markers: Array(0).fill(null) });

  }
  render(){
    const markers = this.state.markers.slice();
    const Markers = markers.map((marker, i)=> {
      return (<Marker key={marker.id} x={marker.position.x} y={marker.position.y} />)

    });
    return(
        <div className="row">
            <div className="col-sm-9">
              <div id="boardImage"  style={{position: 'relative'}}>
                <img src="http://127.0.0.1:8887/images/Newcastle.jpg" onClick={this.addMarker}  width="100%"/>
                {Markers}
              </div>
            </div>
            <div className="col-sm-3">
              <button onClick={this.undo}>Undo</button>
              <button onClick={this.clearMarkers}>Clear Holds</button>
            </div>
        </div>

    );
  }

}

ReactDOM.render(
  <Board />,
  document.getElementById('boardApp')
);

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoardTopo</title>
    <%= csrf_meta_tags %>
    <script src="https://code.jquery.com/jquery-2.2.4.js" integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI=" crossorigin="anonymous"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <%= yield %>
    </div>
  </body>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.24.0/babel.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fetch/2.0.3/fetch.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react-dom.js"></script>
</html>

app/views/problems/index.html.erb
<h1><%=@board.name%></h1>
<ul>
  <% @board.problems.each do |problem| %>
   <li>
     <%= link_to problem.name, [@board, problem] %>
   </li>
 <% end %>
</ul>

app/views/problems/new.html.erb
<h1><%=@board.name%></h1>
<div class="row">
  <div class="col-sm-12">
    <div id="boardApp" />
  </div>
</div>
<script type="text/babel">
let boardImage = document.getElementById('boardApp').getElementsByTagName("img")[0];
const board_id = <%= @board.id %>;
const boardHolds = (<%=raw @board.holds.to_json %>).map((hold) => {return { id: hold.id, position:{x: hold.x, y: hold.y}, highlight: false}});
class Marker extends React.Component{
  constructor (props) {
    super(props);
    this.state = {highlight:this.props.highlight};

  }

  render() {
    const markerPosition = {position: 'absolute', left: this.props.x * 100 + '%', top: this.props.y * 100+ '%'};
    const strokeColour = this.props.highlight ? 'red' : 'grey';
    return (
      <svg width="3%" height="3%" style={markerPosition} xmlns="http://www.w3.org/2000/svg" onClick={this.props.onClick}>
        <circle cx="50%" cy="50%" r="45%" stroke={strokeColour} stroke-width="5" fill="none" fill-opacity="0.25"  />
      </svg>
    )
  }
};
class Menu extends React.Component{
  constructor (props) {
    super(props);
  }
  render(){
    return(
      <div clas="form">
        <div className="form-group">
          <label for="name">Name Your Problem</label>
          <input name="name" type="text" placeholder="Problem name..." className="form-control" onChange={this.props.onChange} />
        </div>
        <div className="form-group">
          <button className="btn btn-primary" onClick={this.props.onSubmit}>Save Problem</button>
        </div>
      </div>
    )
  }
}
class Board extends React.Component{
  constructor (props) {
    super(props);
    this.state = { holds: boardHolds };
    this.highlightHold = this.highlightHold.bind(this);
    this.saveProblem = this.saveProblem.bind(this);
    this.updateName = this.updateName.bind(this);

  }
  highlightHold(e, id){
    let index = getIndex(id, this.state.holds, "id");

    if(typeof index === 'undefined')
    {
      return;
    }
    else
    {
      let holds = this.state.holds.slice();

      holds[index].highlight = !holds[index].highlight;

      this.setState({holds: holds});

    }

  }
  updateName(e){
    this.setState({name: e.target.value});
  }

  saveProblem(){
    const holds = this.state.holds.slice()
                  .filter((a) => {return a.highlight});
    const problem = {
      board_id: board_id,
      name: this.state.name
    };
    fetch('/boards/' + board_id + '/problems/', {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({problem: problem, holds: holds})
    }).then((response)=>{
      return response.json()
    });
  }

  render(){
    const holds = this.state.holds.slice();
    const holdMarkers = holds.map((marker, i)=> {
      return (<Marker key={marker.id} x={marker.position.x} y={marker.position.y} highlight={marker.highlight} onClick={(e) => this.highlightHold(e, marker.id)}/>)
    });
    return(
        <div className="row">
          <div className="col-sm-9">
            <div style={{position: 'relative'}}>
              <img src="http://127.0.0.1:8887/images/Newcastle.jpg"  width="100%"/>
              {holdMarkers}
            </div>
          </div>
          <div className="col-sm-3">
            <Menu onChange={this.updateName} onSubmit={this.saveProblem}/>
          </div>
        </div>

    );
  }

}

ReactDOM.render(
  <Board />,
  document.getElementById('boardApp')
);

function getIndex(value, arr, prop) {
    for(var i = 0; i < arr.length; i++) {
        if(arr[i][prop] === value) {
            return i;
        }
    }
    return -1; //to handle the case where the value doesn't exist
}
</script>

app/views/problems/show.html.erb
<h1><%=@problem.board.name%></h1>
<h2><%=@problem.name%></h2>
<div class="row">
  <div class="col-sm-12">
    <div id="boardApp" />
  </div>
</div>
<script type="text/babel">
let boardImage = document.getElementById('boardApp').getElementsByTagName("img")[0];
const board_id = <%= @problem.board.id %>;
const boardHolds = (<%=raw @holds.to_json %>).map((hold) => {return { id: hold.id, position:{x: hold.x, y: hold.y}, highlight: false}});
class Marker extends React.Component{
  constructor (props) {
    super(props);
    this.state = {highlight:this.props.highlight};

  }

  render() {
    const markerPosition = {position: 'absolute', left: this.props.x * 100 + '%', top: this.props.y * 100+ '%'};
    return (
      <svg width="3%" height="3%" style={markerPosition} xmlns="http://www.w3.org/2000/svg" onClick={this.props.onClick}>
        <circle cx="50%" cy="50%" r="45%" stroke='red' stroke-width="5" fill="none" fill-opacity="0.25"  />
      </svg>
    )
  }
};
class Board extends React.Component{
  constructor (props) {
    super(props);
    this.state = { holds: boardHolds };
  }

  render(){
    const holds = this.state.holds.slice();
    const holdMarkers = holds.map((marker, i)=> {
      return (<Marker key={marker.id} x={marker.position.x} y={marker.position.y} highlight={marker.highlight} onClick={(e) => this.highlightHold(e, marker.id)}/>)
    });
    return(
        <div className="row">
          <div className="col-sm-9">
            <div style={{position: 'relative'}}>
              <img src="http://127.0.0.1:8887/images/Newcastle.jpg"  width="100%"/>
              {holdMarkers}
            </div>
          </div>
          <div className="col-sm-3">
          </div>
        </div>

    );
  }

}

ReactDOM.render(
  <Board />,
  document.getElementById('boardApp')
);

function getIndex(value, arr, prop) {
    for(var i = 0; i < arr.length; i++) {
        if(arr[i][prop] === value) {
            return i;
        }
    }
    return -1; //to handle the case where the value doesn't exist
}
</script>